# The Basics
dist: trusty
language: java
jdk:
- oraclejdk8

script: ./gradlew build
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" = "develop" ]; then ./gradlew uploadArchives; fi

# Ugh.
notifications:
  email: false
